version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          package-manager: 'yarn'
          start-command: 'yarn cy:run --browser chrome'