version: 2.1
orbs:
  cypress: cypress-io/cypress@3
  slack: circleci/slack@5.1.1

jobs:
  run-cypress:
    docker:
      - image: cypress/included:14.0.0
    steps:
      - run:
          name: Fix Git safe directory issue
          command: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run:
          name: Debug checkout
          command: ls -la
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Install CURL
          command: apt-get update && apt-get install -y curl
      - run:
          name: Run Cypress Tests
          command: yarn cy:run
      - run:
          name: Wait for report generation
          command: sleep 10
      - store_artifacts:
          name: Uploading HTML Report
          path: cypress/reports/html
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Cypress Test Failed! :shipit:*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n${CIRCLE_SHA1}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Action Required:*\nPlease check the logs and investigate the failure."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "🔍 View Logs"
                      },
                      "url": "${CIRCLE_BUILD_URL}",
                      "style": "primary"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "📑 Check Report"
                      },
                      "url": "https://output.circle-artifacts.com/output/job/${CIRCLE_BUILD_NUM}/artifacts/0/cypress/reports/html/index.html",
                      "style": "primary"
                    }
                  ]
                }
              ]
            }
          channel: "#reports"

workflows:
  run-cypress-tests:
    jobs:
      - run-cypress:
          context:
            - cypress-context
