version: 2.1
orbs:
  cypress: cypress-io/cypress@3

jobs:
  run-cypress:
    executor: cypress/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run Cypress Tests
          command: yarn cy:run
      - store_artifacts:
          name: Uploading HTML Report
          path: cypress/reports/html/index.html

workflows:
  run-cypress-tests:
    jobs:
      - run-cypress